// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThrashGroups.Context;

#nullable disable

namespace ThrashGroups.Migrations.DataGroups
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240120041406_AddIndexToStudentGroup")]
    partial class AddIndexToStudentGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThrashGroups.Entity.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ThrashGroups.Entity.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Middlename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ThrashGroups.Entity.StudentGroup", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "GroupId", "Type");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_TypeCondition")
                        .HasFilter("\"Type\"=1");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("ThrashGroups.Entity.StudentUnderGroup", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("UnderGroupId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "UnderGroupId");

                    b.HasIndex("UnderGroupId");

                    b.ToTable("StudentUnderGroups");
                });

            modelBuilder.Entity("ThrashGroups.Entity.UnderGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("UnderGroups");
                });

            modelBuilder.Entity("ThrashGroups.Entity.StudentGroup", b =>
                {
                    b.HasOne("ThrashGroups.Entity.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThrashGroups.Entity.Student", "Student")
                        .WithMany("StudentGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ThrashGroups.Entity.StudentUnderGroup", b =>
                {
                    b.HasOne("ThrashGroups.Entity.Student", "Student")
                        .WithMany("StudentUnderGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThrashGroups.Entity.UnderGroup", "UnderGroup")
                        .WithMany()
                        .HasForeignKey("UnderGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("UnderGroup");
                });

            modelBuilder.Entity("ThrashGroups.Entity.UnderGroup", b =>
                {
                    b.HasOne("ThrashGroups.Entity.Group", "Group")
                        .WithMany("UnderGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ThrashGroups.Entity.Group", b =>
                {
                    b.Navigation("UnderGroups");
                });

            modelBuilder.Entity("ThrashGroups.Entity.Student", b =>
                {
                    b.Navigation("StudentGroups");

                    b.Navigation("StudentUnderGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
